services:
  api:
    depends_on:
      - mongodb
    container_name: soczew-backend-api
    build: ./api
    working_dir: /code/app
    command: uvicorn server.app:app --proxy-headers --host 0.0.0.0 --port 8090 --reload
    volumes:
      - ./api/app:/code/app
    ports:
      - "8090:8090"
    restart: on-failure
    environment:
      - JWT_SECRET_KEY=example
      
  mongodb:
    image: mongo:7.0.3
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example